### ISSUE TITLE
Initial back-end proof-of-concept

### ISSUE THREAD

**Issue by vijayiyer05** [FZJ-INM1-BDA/siibralab#1]
Initial proof-of-concept functions and scripts showing the following steps: 
- [x] Access of atlas metadata (including spaces & parcellations) via RESTful API
- [x] Query of atlas metadata to identify data of interest
- [ ] Access of atlas data (including images, ROIs, & surfaces) by metadata or ROI query types [(Reference snippet)](https://siibra-python.readthedocs.io/en/latest/examples/02_maps_and_templates/005_access_surface_maps.html#)

To complete this issue, it is suggested there be at least:

- [x] 1 standalone script example illustrating one SIIBRA modality (e.g. MRI, light microscopy) and the steps above

**Comment by vijayiyer05** [comment]
@valentin-pinkau

For the first task above, I had an initial notion there might be more metadata to explore with some of the data objects, including atlases. Currently I see mostly sub-objects (e.g. parcellations) and the data itself. Is there more information about atlases or other objects which could be explored and displayed? Also, could it be possible to get a listing of available atlases?

**Comment by dickscheid** [comment]
>     * [ ]  Query of atlas metadata to identify data of interest

This one so far only adresses access to basic metadata of brain regions, not search for data features. Ok for me to make this part of the next meta task.

**Comment by dickscheid** [comment]
> * Access of atlas data (including images, ROIs, & surfaces) by metadata or ROI query types

this should be demonstrated by displaying a a parcellation volume in 
- a ortho-slice viewer (partly realized in https://github.com/FZJ-INM1-BDA/siibra-matlab/blob/70cbb9bc5b26128f433437b398819b487a177e97/step-by-step/02_maps_and_templates/02_access_brain_reference_templates.mlx)
- a surface mesh viewer (not yet avaible, similar to the [reference snippet](https://siibra-python.readthedocs.io/en/latest/examples/02_maps_and_templates/005_access_surface_maps.html#)

**Comment by vijayiyer05** [comment]
> > ```
> > * [ ]  Query of atlas metadata to identify data of interest
> > ```
> 
> This one so far only adresses access to basic metadata of brain regions, not search for data features. Ok for me to make this part of the next meta task.

I think (my) initial phrasing could likely have been better here. Intended meaning was closer to "query by atlas metadata to access item of interest". 

The `metadata.mlx` script achieves what was meant, showing both the retrieval of metadata and the access of items based on that metadata.

**Comment by vijayiyer05** [comment]
> > * Access of atlas data (including images, ROIs, & surfaces) by metadata or ROI query types
> 
> this should be demonstrated by displaying a a parcellation volume in
> 
> * a ortho-slice viewer (partly realized in https://github.com/FZJ-INM1-BDA/siibra-matlab/blob/70cbb9bc5b26128f433437b398819b487a177e97/step-by-step/02_maps_and_templates/02_access_brain_reference_templates.mlx)
> * a surface mesh viewer (not yet avaible, similar to the [reference snippet](https://siibra-python.readthedocs.io/en/latest/examples/02_maps_and_templates/005_access_surface_maps.html#)

Carrying this over to Issue #18.

**Comment by vijayiyer05** [comment]
> 
> To complete this issue, it is suggested there be at least:
> 
> * [ ]  1 standalone script example illustrating one SIIBRA modality (e.g. MRI, light microscopy) and the steps above

This intermediate step was skipped over, immediately achieving the live scripts as planned for #2.

**Comment by vijayiyer05** [comment]
All tasks completed, carried over, or obviated. 

Closing issue.
