### ISSUE TITLE
Initial front-end command-line interface implementation 

### ISSUE THREAD

**Issue by vijayiyer05** [FZJ-INM1-BDA/siibralab#2]
An initial working prototype for the "Siibra toolbox" should include the following elements:

- [x] Object-oriented command-line interface (CLI), including classes mapped to Siibra constructs and methods for the various operations from #1 
- [x] Adaptation of suited MATLAB types for data representatoins of Siibra constructs. Possibilities might be: [tables](https://www.mathworks.com/help/matlab/tables.html) for metadata and [blocked image](https://www.mathworks.com/help/images/large-image-files.html) for large image data.

To demonstrate this prototype, the following are suggested:
- [x] Update standalone test script from #1  into an example script applying the object-oriented CLI 
- [ ] Add new example script covering a new SIIBRA use case (e.g. MRI, optical microscopy),  preferably in a [live script](https://www.mathworks.com/help/matlab/matlab_prog/what-is-a-live-script-or-function.html) format including some narrative text and graphical outputs

**Comment by dickscheid** [comment]
I would consider this done, since we have the walkthrough live script, although it does not demonstrate microscopy. This will be a future feature.
